global:
  edition: community
  instanceId: "airbyte-local"
  database:
    type: external
    host: "172.17.0.1"
    port: "5432"
    user: "airbyte"
    password: "airbyte123"
    configs:
      database: "airbyte"
    jobs:
      database: "airbyte_jobs"

postgresql:
  enabled: false

externalDatabase:
  type: postgres
  host: "172.17.0.1"
  port: 5432
  database: "airbyte"
  user: "airbyte"
  password: "airbyte123"
  jdbcUrl: "jdbc:postgresql://172.17.0.1:5432/airbyte"

webapp:
  service:
    type: NodePort
    port: 80

server:
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

worker:
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

bootloader:
  extraEnv:
    - name: DATABASE_DB
      value: "airbyte"
    - name: DATABASE_URL
      value: "jdbc:postgresql://172.17.0.1:5432/airbyte"
    - name: CONFIGS_DATABASE_NAME
      value: "airbyte"
    - name: JOBS_DATABASE_NAME
      value: "airbyte_jobs"