global:
  edition: community
  instanceId: "airbyte-local"
  image:
    pullPolicy: IfNotPresent  # Use cached images if available
    tag: "1.8.5"  # Pin to specific version (check your current version)
  database:
    type: external
    host: "172.17.0.1"
    port: "5432"
    user: "airbyte"
    password: "airbyte123"

postgresql:
  enabled: false

externalDatabase:
  type: postgres
  host: "172.17.0.1"
  port: 5432
  database: "db-airbyte"
  user: "airbyte"
  password: "airbyte123"
  jdbcUrl: "jdbc:postgresql://172.17.0.1:5432/db-airbyte"

webapp:
  service:
    type: NodePort
    port: 80

server:
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

worker:
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "2000m"